name: Delete untagged images

on:
  workflow_dispatch:

jobs:
  delete_images:
    runs-on: ubuntu-latest
    steps:
    - name: Delete all containers from repository without tags
      uses: Chizkiyahu/delete-untagged-ghcr-action@v6
      with:
          token: ${{ secrets.PAT_TOKEN }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          untagged_only: true
          owner_type: user
