name: Promote to beta

on:
  workflow_dispatch:

jobs:
  promote_to_latest:
    runs-on: ubuntu-latest
    name: Promote from develop to beta 
    
    strategy:
      fail-fast: false
      matrix:
        name: [
          'aio-alpine',
          'aio-apache',
          'aio-borgbackup',
          'aio-collabora',
          'aio-domaincheck',
          'all-in-one',
          'aio-nextcloud',
          'aio-notify-push',
          'aio-postgresql',
          'aio-redis',
          'aio-talk',
          'aio-watchtower',
          'aio-clamav',
          'aio-onlyoffice',
          'aio-imaginary',
          'aio-talk-recording',
          'aio-fulltextsearch',
          'aio-docker-socket-proxy',
          'aio-whiteboard']

    steps:
    - name: Login to ghcr.io
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Promote images from develop to beta (create multiarch) on ghcr.io
      run: |
        set -x
        AIO_NAME=${{ matrix.name }}
        set +x
        
        # create multiarch image
        docker buildx imagetools create --tag ghcr.io/koendiender/$AIO_NAME\:beta ghcr.io/koendiender/$AIO_NAME\:develop ghcr.io/koendiender/$AIO_NAME\:develop-arm64

        # arm64
        docker buildx imagetools create --tag ghcr.io/koendiender/$AIO_NAME\:beta-arm64 ghcr.io/koendiender/$AIO_NAME\:develop ghcr.io/koendiender/$AIO_NAME\:develop-arm64
